# Generated by Django 4.2.8 on 2025-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Price in INR')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('blog_limit', models.PositiveIntegerField(help_text='Number of blogs allowed per cycle')),
                ('image_limit', models.PositiveIntegerField(help_text='Number of images allowed per cycle')),
                ('is_active', models.BooleanField(default=True)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
