# Generated by Django 4.2.8 on 2025-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_usersubscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='razorpay_subscription_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
