# Generated by Django 4.2.8 on 2025-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_razorpay_subscription_id_usersubscription_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
