# Generated by Django 4.2.8 on 2025-12-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_planfeature_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='grandfathered_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of plan features and limits at time of subscription', null=True),
        ),
    ]
