  version: "3.9"

  services:

    db:
      container_name: myproject_db
      image: postgres:16
      restart: always
      environment:
        POSTGRES_DB: myproject
        POSTGRES_USER: myprojectuser
        POSTGRES_PASSWORD: myproject@123
      ports:
        - "5433:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

    redis:
      container_name: myproject_redis
      image: redis:7
      restart: always
      ports:
        - "6379:6379"

    mqtt:
      container_name: myproject_mqtt
      image: eclipse-mosquitto
      restart: always
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - ./mosquitto/config:/mosquitto/config
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log

    # -------------------------
    # ELK STACK
    # -------------------------
    elasticsearch:
      container_name: myproject_elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
      ports:
        - "9200:9200"
      volumes:
        - esdata:/usr/share/elasticsearch/data
      restart: always

    logstash:
      container_name: myproject_logstash
      image: docker.elastic.co/logstash/logstash:8.12.2
      volumes:
        - ./logstash/pipeline:/usr/share/logstash/pipeline
      ports:
        - "5044:5044"
      depends_on:
        - elasticsearch
      restart: always

    kibana:
      container_name: myproject_kibana
      image: docker.elastic.co/kibana/kibana:8.12.2
      ports:
        - "5602:5601"
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      depends_on:
        - elasticsearch
      restart: always

    # -------------------------
    # DJANGO WEB
    # -------------------------
    web:
      container_name: myproject_web
      build: .
      restart: always
      entrypoint: ["/app/entrypoint.sh"]
      command: >
        sh -c "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
        - redis
        - logstash
      environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: myprojectuser
        POSTGRES_PASSWORD: myproject@123
        POSTGRES_DB: myproject
        REDIS_HOST: redis
        REDIS_PORT: 6379
        RUN_MIGRATIONS: "true"


    # -------------------------
    # CELERY WORKER
    # -------------------------
    celery:
      container_name: myproject_celery
      build: .
      restart: always
      entrypoint: ["/app/entrypoint.sh"]
      command: >
        sh -c "python manage.py migrate &&
              celery -A myproject worker --loglevel=info"
      volumes:
        - .:/app
      depends_on:
        - db
        - redis
        - logstash
      environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: myprojectuser
        POSTGRES_PASSWORD: myproject@123
        POSTGRES_DB: myproject
        RUN_MIGRATIONS: "false" 

    # -------------------------
    # CELERY BEAT
    # -------------------------
    celery_beat:
      container_name: myproject_celery_beat
      build: .
      restart: always
      entrypoint: ["/app/entrypoint.sh"]
      command: >
        sh -c "python manage.py migrate &&
              celery -A myproject beat --loglevel=info"
      volumes:
        - .:/app
      depends_on:
        - db
        - redis
        - logstash
      environment:
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: myprojectuser
        POSTGRES_PASSWORD: myproject@123
        POSTGRES_DB: myproject

    # -------------------------
    # MQTT SUBSCRIBER (UPDATED)
    # -------------------------
    subscriber:
      container_name: myproject_subscriber
      build: .
      restart: always
      command: python blog_app/mqtt_subscriber.py
      volumes:
        - .:/app
      depends_on:
        - mqtt
        - logstash
      environment:
        # MQTT CONFIG (IMPORTANT)
        MQTT_HOST: mqtt
        MQTT_PORT: 1883
        MQTT_USERNAME: admin
        MQTT_PASSWORD: ayush123
        RUN_MIGRATIONS: "false"

        # DB (if subscriber ever needs it)
        POSTGRES_HOST: db
        POSTGRES_PORT: 5432
        POSTGRES_USER: myprojectuser
        POSTGRES_PASSWORD: myproject@123
        POSTGRES_DB: myproject



  volumes:
    pgdata:
    esdata:
