# Generated by Django 4.2.8 on 2025-11-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_is_published_unpublishlog_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnpublishLog',
        ),
    ]
