# Generated by Django 4.2.8 on 2025-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_delete_unpublishlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
