# Generated by Django 4.2.8 on 2025-12-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='author_logos/'),
        ),
    ]
