# Generated by Django 4.2.8 on 2025-12-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Business Admin'), ('author', 'Author'), ('user', 'Normal User')], default='user', max_length=20),
        ),
    ]
