# Generated by Django 4.2.8 on 2025-12-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_blog_image_blog_is_password_protected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='theme_id',
        ),
    ]
