# Generated by Django 4.2.8 on 2026-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_remove_blog_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Indicates if the blog content was generated by AI'),
        ),
        migrations.AddField(
            model_name='blog',
            name='ai_generation_prompt',
            field=models.TextField(blank=True, help_text='Prompt used to generate this blog via AI', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ai_improved_content',
            field=models.TextField(blank=True, help_text='AI-improved version of the blog content', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the blog', null=True),
        ),
    ]
