# Generated by Django 4.2.8 on 2026-03-30 13:20

import blog_app.audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Generated audio file (MP3)', null=True, upload_to=blog_app.audio.models.audio_file_path),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Audio duration in seconds'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if generation failed'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Audio file expiration time (for cleanup)', null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिंदी)'), ('gu', 'Gujarati (ગુજરાતી)')], default='en', help_text='Audio language', max_length=5),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='mode',
            field=models.CharField(choices=[('conversation', 'Conversation (Podcast Style)'), ('explain', 'Explain (Teacher Style)'), ('summary', 'Summary (Quick Overview)')], default='explain', help_text='Audio transformation mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='mood',
            field=models.CharField(choices=[('serious', 'Serious - Professional tone'), ('storytelling', 'Storytelling - Narrative with dramatic elements'), ('educational', 'Educational - Clear, structured delivery')], default='educational', help_text='Voice style/mood', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='questions',
            field=models.JSONField(default=list, help_text='AI-generated comprehension questions'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='sections',
            field=models.JSONField(default=dict, help_text='Section timestamps: {intro: {start, end}, main: {...}, conclusion: {...}}'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Audio generation in queue'), ('processing', 'Processing - Audio being generated'), ('ready', 'Ready - Audio available for playback'), ('failed', 'Failed - Audio generation error')], default='pending', help_text='Audio generation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='suggestions',
            field=models.JSONField(default=list, help_text='AI suggestions for other modes/languages'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='summary',
            field=models.TextField(default='', help_text='AI-generated summary'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='transcript',
            field=models.TextField(default='', help_text='Full transcript of the audio'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='understanding_level',
            field=models.CharField(choices=[('beginner', 'Beginner - Simple explanations with analogies'), ('intermediate', 'Intermediate - Balanced depth and accessibility'), ('expert', 'Expert - Technical terms, focused insights')], default='intermediate', help_text='Content complexity level', max_length=15),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='correct_answer',
            field=models.CharField(help_text='The correct answer', max_length=500),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer'),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='options',
            field=models.JSONField(default=list, help_text='Multiple choice options for this question'),
        ),
        migrations.AlterField(
            model_name='audioquestion',
            name='question',
            field=models.TextField(help_text='The question text'),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='autoplay',
            field=models.BooleanField(default=False, help_text='Auto-play audio when blog loads'),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिंदी)'), ('gu', 'Gujarati (ગુજરાતી)')], default='en', help_text="User's preferred language", max_length=5),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_mode',
            field=models.CharField(choices=[('conversation', 'Conversation (Podcast Style)'), ('explain', 'Explain (Teacher Style)'), ('summary', 'Summary (Quick Overview)')], default='explain', help_text="User's preferred audio mode", max_length=20),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_mood',
            field=models.CharField(choices=[('serious', 'Serious - Professional tone'), ('storytelling', 'Storytelling - Narrative with dramatic elements'), ('educational', 'Educational - Clear, structured delivery')], default='educational', help_text="User's preferred voice mood", max_length=20),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_speed',
            field=models.FloatField(default=1.0, help_text='Default playback speed (0.5 - 2.0)'),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_understanding_level',
            field=models.CharField(choices=[('beginner', 'Beginner - Simple explanations with analogies'), ('intermediate', 'Intermediate - Balanced depth and accessibility'), ('expert', 'Expert - Technical terms, focused insights')], default='intermediate', help_text="User's preferred understanding level", max_length=15),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='default_volume',
            field=models.FloatField(default=0.8, help_text='Default volume (0.0 - 1.0)'),
        ),
        migrations.AlterField(
            model_name='useraudiopreference',
            name='highlight_sync_enabled',
            field=models.BooleanField(default=True, help_text='Enable text highlighting sync during playback'),
        ),
        migrations.DeleteModel(
            name='AudioBookmark',
        ),
    ]
